---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  OTBR_VERSION: 2f3c799c7463c8f674754e65c53f78bc0bbcbd58 #  Thread Reference 2025-06-12
  UNIVERSAL_SILABS_FLASHER_VERSION: 0.1.2
  SERIALX_VERSION: 0.5.0
