---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  # Thread Reference 2025-06-12
  OTBR_VERSION: thread-reference-20250612
  UNIVERSAL_SILABS_FLASHER_VERSION: 0.1.2
  SERIALX_VERSION: 0.5.0
