---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
args:
  OTBR_VERSION: 624a7d98e0dac5984c2982068f71fc81d2dbceb5
  UNIVERSAL_SILABS_FLASHER_VERSION: 0.1.2
  SERIALX_VERSION: 0.5.0
