---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  OTBR_VERSION: 09574a202c2b4690910dd909c81d127426d3663e
  UNIVERSAL_SILABS_FLASHER: 0.0.22
