---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
args:
  OTBR_BETA_VERSION: 0b14f77ab62d49edd3a14d9a294bbdfd95a4e74c
  OTBR_VERSION: 624a7d98e0dac5984c2982068f71fc81d2dbceb5
  UNIVERSAL_SILABS_FLASHER_VERSION: 0.1.2
  SERIALX_VERSION: 1.8.0
