---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
args:
  OTBR_BETA_VERSION: 4e5cfca4cc8c37fed43aec60cdbbe5df0be90d69
  OTBR_VERSION: 4e5cfca4cc8c37fed43aec60cdbbe5df0be90d69
  UNIVERSAL_SILABS_FLASHER_VERSION: 0.1.2
  SERIALX_VERSION: 1.8.0
