---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23-2025.12.2
  amd64: ghcr.io/home-assistant/amd64-base:3.23-2025.12.2
args:
  CLI_VERSION: 4.46.0
  LIBWEBSOCKETS_VERSION: 4.4.1
  TTYD_VERSION: 1.7.7
