---
version: 12.6.1
slug: samba
name: Samba share
description: Expose Home Assistant folders with SMB/CIFS
url: https://github.com/home-assistant/addons/tree/master/samba
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
image: homeassistant/{arch}-addon-samba
init: false
map:
  - type: addons
    read_only: false
    path: "/smbshare/addons"
  - type: all_addon_configs
    read_only: false
    path: "/smbshare/addon_configs"
  - type: backup
    read_only: false
    path: "/smbshare/backup"
  - type: homeassistant_config
    read_only: false
    path: "/smbshare/homeassistant"
  - type: media
    read_only: false
    path: "/smbshare/media"
  - type: share
    read_only: false
    path: "/smbshare/share"
  - type: ssl
    read_only: false
    path: "/smbshare/ssl"
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  enabled_shares:
    - addons
    - addon_configs
    - backup
    - config
    - media
    - share
    - ssl
  local_master: true
  compatibility_mode: false
  apple_compatibility_mode: true
  server_signing: "default"
  netbios: true
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 169.254.0.0/16
    - fe80::/10
    - fc00::/7
schema:
  username: str
  password: password
  workgroup: str
  enabled_shares:
    - "match(^(?i:(addons|addon_configs|backup|config|media|share|ssl))$)"
  local_master: bool
  compatibility_mode: bool
  apple_compatibility_mode: bool
  server_signing: list(default|auto|mandatory|disabled)
  netbios: bool
  veto_files:
    - str
  allow_hosts:
    - str
startup: services
ports:
  445/tcp: null
  139/tcp: null
ports_description:
  445/tcp: SMB over IP
  139/tcp: SMB over NetBIOS