---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
args:
  CPCD_VERSION: v4.3.1
  GECKO_SDK_VERSION: v4.3.1
  UNIVERSAL_SILABS_FLASHER: 0.0.13
