#!/bin/sh

declare thread_if
declare otbr_forward_ingress_chain
declare otbr_forward_egress_chain
thread_if="wpan0"
otbr_forward_ingress_chain="OTBR_FORWARD_INGRESS"
otbr_forward_egress_chain="OTBR_FORWARD_EGRESS"

