---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:buster
  amd64: ghcr.io/home-assistant/amd64-base-debian:buster
  armv7: ghcr.io/home-assistant/armv7-base-debian:buster
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ALMOND_VERSION: v2.0.1
