---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
args:
  LIBWEBSOCKET_VERSION: 4.5.8
  MOSQUITTO_VERSION: 2.1.2
  MOSQUITTO_AUTH_VERSION: 3.0.0
