---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
args:
  LIBWEBSOCKET_VERSION: 4.3.3
  MOSQUITTO_VERSION: 2.0.22
  MOSQUITTO_AUTH_VERSION: 2.1.0
