---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:buster
  amd64: ghcr.io/home-assistant/amd64-base-debian:buster
  armhf: ghcr.io/home-assistant/armhf-base-raspbian:buster
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  DECONZ_VERSION: 2.27.6
