---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie
args:
  WYOMING_WHISPER_VERSION: 3.5.0
  WYOMING_VERSION: 1.9.0
  # Must match the exact pins of wyoming-faster-whisper
  TRANSFORMERS_VERSION: 4.52.4
  ONNX_ASR_VERSION: 0.11.0
  FUNASR_VERSION: 1.4.3
  ONNXRUNTIME_VERSION: 1.29.0
  FASTER_WHISPER_VERSION: 1.2.1
  CTRANSLATE2_VERSION: 4.8.1
  SHERPA_ONNX_VERSION: 1.13.6
  TORCH_VERSION: 2.7.1
