---
version: 2.4.6
slug: silabs_multiprotocol_dev
name: Silicon Labs Multiprotocol dev
description: Zigbee and OpenThread multiprotocol add-on dev
url: >
  https://github.com/regevbr/addons/tree/master/silabs-multiprotocol_dev
arch:
  - armv7
  - aarch64
  - amd64
homeassistant: 2024.1.0
gpio: true
hassio_api: true
discovery:
  - otbr
# IPC is only used within the Add-on
host_ipc: false
host_network: true
host_uts: true
privileged:
  - IPC_LOCK
  - NET_ADMIN
image: homeassistant/{arch}-addon-silabs-multiprotocol_dev
init: false
options:
  device: null
  baudrate: "460800"
  flow_control: true
  autoflash_firmware: true
  cpcd_trace: false
  otbr_enable: true
  otbr_log_level: notice
  otbr_firewall: true
  otbr_nat64: false
ports:
  9999/tcp: null
  8080/tcp: null
  8081/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
  8080/tcp: OpenThread Web port
  8081/tcp: OpenThread REST API port
schema:
  device: device(subsystem=tty)?
  baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  network_device: str?
  autoflash_firmware: bool
  cpcd_trace: bool
  otbr_enable: bool
  otbr_log_level: list(debug|info|notice|warning|error|critical|alert|emergency)
  otbr_firewall: bool
  otbr_nat64: bool
stage: experimental
startup: services
