---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ZWAVEJS_SERVER_VERSION: 1.28.0
  ZWAVEJS_VERSION: 10.17.0
