---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
  amd64: ghcr.io/home-assistant/amd64-base:3.21
  armhf: ghcr.io/home-assistant/armhf-base:3.21
  armv7: ghcr.io/home-assistant/armv7-base:3.21
  i386: ghcr.io/home-assistant/i386-base:3.21
args:
  ZWAVEJS_SERVER_VERSION: 3.4.0
  ZWAVEJS_VERSION: 15.15.0
