---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.12
  amd64: ghcr.io/home-assistant/amd64-base:3.12
  armhf: ghcr.io/home-assistant/armhf-base:3.12
  armv7: ghcr.io/home-assistant/armv7-base:3.12
  i386: ghcr.io/home-assistant/i386-base:3.12
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
