---
build_from:
  aarch64: ghcr.io/matter-js/python-matter-server:8.1.2
  amd64: ghcr.io/matter-js/python-matter-server:8.1.2
args:
  BASHIO_VERSION: 0.17.1
  TEMPIO_VERSION: 2024.11.2
  S6_OVERLAY_VERSION: 3.1.6.2
