---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16
  amd64: ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16
  armhf: ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16
  armv7: ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16
  i386: ghcr.io/home-assistant/i386-base-python:3.10-alpine3.16
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  CRYPTOGRAPHY_VERSION: 36.0.2
  CERTBOT_DNS_AZURE_VERSION: 1.5.0
  CERTBOT_DNS_DIRECTADMIN_VERSION: 0.0.24
  CERTBOT_DNS_HETZNER_VERSION: 1.0.5
  CERTBOT_DNS_TRANSIP_VERSION: 0.4.3
  CERTBOT_GANDI_VERSION: 1.3.2
  CERTBOT_NETCUP_VERSION: 1.1.1
  CERTBOT_NJALLA_VERSION: 1.0.0
  CERTBOT_VERSION: 1.32.0
  CERTBOT_DNS_INWX_VERSION: 2.2.0
  ACME_VERSION: 1.32.0
