---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:trixie-2025.12.2
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie-2025.12.2
args:
  ACME_VERSION: 3.3.0
  # certbot-dns-multi replaces most individual DNS plugins using lego
  CERTBOT_DNS_MULTI_VERSION: 4.30.1
  # Only legacy plugins are kept for providers not supported by lego:
  # gehirn, eurodns, noris
  CERTBOT_DNS_EURODNS_VERSION: 1.8.1
  CERTBOT_DNS_NORISNETWORK_VERSION: 0.3.0
  # Azure and HE kept as legacy for backward compatibility
  # (provider supported by lego, will be removed in future version)
  CERTBOT_DNS_AZURE_VERSION: 2.6.1
  CERTBOT_DNS_HURRICANE_ELECTRIC_VERSION: 0.1.0
  CERTBOT_VERSION: 3.3.0
  CRYPTOGRAPHY_VERSION: 44.0.2
