#!/usr/bin/with-contenv bashio
# shellcheck shell=bash
# ==============================================================================
# Init folder & structures
# ==============================================================================
mkdir -p /data/workdir
mkdir -p /data/letsencrypt

DNS_API_KEY=/data/dnsapikey
DNS_MULTI_CREDS=/data/dns-multi.ini

touch "${DNS_API_KEY}"
chmod 0600 "${DNS_API_KEY}"

echo "# generated by letsencrypt app startup script" > "${DNS_MULTI_CREDS}"
chmod 0600 "${DNS_MULTI_CREDS}"

if bashio::config.exists 'dns.google_creds'; then
    GOOGLE_CREDS="$(bashio::config 'dns.google_creds')"
    if [ -f "/share/${GOOGLE_CREDS}" ]; then
        cp -f "/share/${GOOGLE_CREDS}" "/data/google.json"
        chmod 0600 "/data/google.json"
    else
        bashio::log.error "Google credentials file '${GOOGLE_CREDS}' not found in /share directory"
        exit 1
    fi
fi

if bashio::config.exists 'dns.azure_config'; then
    bashio::log.warning "Using legacy certbot-dns-azure plugin (DEPRECATED)"
    bashio::log.warning "The 'azure_config' option will be removed in a future version."
    AZURE_CREDS="$(bashio::config 'dns.azure_config')"
    if [ -f "/share/${AZURE_CREDS}" ]; then
        cp -f "/share/${AZURE_CREDS}" "/data/azure_creds"
        chmod 0600 "/data/azure_creds"
    else
        bashio::log.error "Azure credentials file '${AZURE_CREDS}' not found in /share directory"
        exit 1
    fi
fi

# Warn/fail on deprecated options
if bashio::config.has_value 'dns.cloudns_sub_auth_user'; then
    bashio::log.error "cloudns_sub_auth_user is not supported since Letsencrypt Home Assistant App v6.0.0."
    exit 1
fi


if bashio::config.has_value 'dns.dreamhost_baseurl'; then
    if [ "$(bashio::config 'dns.dreamhost_baseurl')" != "https://api.dreamhost.com/" ]; then
        bashio::log.error "dreamhost_baseurl is not supported since Letsencrypt Home Assistant App v6.0.0."
        exit 1
    else
        bashio::log.warning "dreamhost_baseurl is not required since Letsencrypt Home Assistant App v6.0.0, please remove it from your configuration."
    fi
fi

if bashio::config.has_value 'dns.gandi_sharing_id'; then
    bashio::log.error "gandi_sharing_id is not supported since Letsencrypt Home Assistant App v6.0.0."
    exit 1
fi

if bashio::config.has_value 'dns.ionos_endpoint'; then
    if [ "$(bashio::config 'dns.ionos_endpoint')" != "https://api.hosting.ionos.com" ]; then
        bashio::log.error "ionos_endpoint is not supported since Letsencrypt Home Assistant App v6.0.0."
        exit 1
    else
        bashio::log.warning "ionos_endpoint is not required since Letsencrypt Home Assistant App v6.0.0, please remove it from your configuration."
    fi
fi

if bashio::config.has_value 'dns.joker_domain'; then
    bashio::log.error "joker_domain is not supported since Letsencrypt Home Assistant App v6.0.0."
    exit 1
fi

if bashio::config.has_value 'dns.linode_version'; then
    if [ "$(bashio::config 'dns.linode_version')" != "4" ]; then
        bashio::log.error "Only Linode API v4 is supported since Letsencrypt Home Assistant App v6.0.0."
        exit 1
    else
        bashio::log.warning "linode_version is not required since Letsencrypt Home Assistant App v6.0.0, please remove it from your configuration."
    fi
fi

if bashio::config.has_value 'dns.rfc2136_sign_query'; then
    bashio::log.error "rfc2136_sign_query is not supported since Letsencrypt Home Assistant App v6.0.0."
    exit 1
fi

if bashio::config.has_value 'dns.transip_global_key'; then
    bashio::log.error "transip_global_key is not supported since Letsencrypt Home Assistant App v6.0.0."
    exit 1
fi

# Cleanup removed add-on options
if bashio::config.exists 'dns.cloudxns_api_key'; then
    bashio::addon.option 'dns.cloudxns_api_key'
fi
if bashio::config.exists 'dns.cloudxns_secret_key'; then
    bashio::addon.option 'dns.cloudxns_secret_key'
fi
if bashio::config.exists 'keytype'; then
    bashio::addon.option 'keytype'
fi
if bashio::config.exists 'dns.google_domains_access_token'; then
    bashio::addon.option 'dns.google_domains_access_token'
fi
if bashio::config.exists 'dns.google_domains_zone'; then
    bashio::addon.option 'dns.google_domains_zone'
fi
